### ISSUE TITLE
Z80 Undocumented Instructions

### ISSUE THREAD

**Issue by Tolik-Trek** [maziac/z80-instruction-set#12]
Please add some missing instructions like "SET r,0,(IX+nn)    DD CB nn C0+r"
Information:
http://www.z80.info/z80undoc.htm

**Comment by maziac** [comment]
I think the used syntax is different: 
SET 0,(ix+n),r

Not sure what is the official syntax for undocumented instructions :-)

**Comment by Tolik-Trek** [comment]
> I think the used syntax is different: 
> 
> SET 0,(ix+n),r
Yes, got to be like that. SjasmPlus understand that syntax.
