### ISSUE TITLE
Don't recognize RST with # number

### ISSUE THREAD

**Issue by Tolik-Trek** [maziac/z80-instruction-set#13]
Hello! It's me again)))
incorrectly recognizes the RST command if the hexadecimal number is specified with a # in front:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/85737314/205484895-5fa2d4a7-4c60-4a9f-811d-d7206013509f.png">

**Comment by maziac** [comment]
Which assembler is this?

**Comment by Tolik-Trek** [comment]
> Which assembler is this?

Zilog Z80

**Comment by maziac** [comment]
Please check this fix:
[z80-instruction-set-1.2.1-rc1.vsix.zip](https://github.com/maziac/z80-instruction-set/files/11076886/z80-instruction-set-1.2.1-rc1.vsix.zip)

**Comment by Tolik-Trek** [comment]
> Please check this fix: [z80-instruction-set-1.2.1-rc1.vsix.zip](https://github.com/maziac/z80-instruction-set/files/11076886/z80-instruction-set-1.2.1-rc1.vsix.zip)

Excellent, it works as it should, thanks)))
