### ISSUE TITLE
Wrong legend inc ix

### ISSUE THREAD

**Issue by denisiorus** [maziac/z80-instruction-set#14]
Legend states **inc ix** means ix:=**iy**+1

**Comment by maziac** [comment]
Thanks for reporting. Will correct it.

**Comment by maziac** [comment]
Please try this one and let me know if it works:
[z80-instruction-set-1.1.2-rc1.vsix.zip](https://github.com/maziac/z80-instruction-set/files/10286750/z80-instruction-set-1.1.2-rc1.vsix.zip)

**Comment by denisiorus** [comment]
Works just fine.
