### ISSUE TITLE
Incorrect description of the effect on the carry flag in I/O commands

### ISSUE THREAD

**Issue by Tolik-Trek** [maziac/z80-instruction-set#15]
The commands OUTI, OUTD, OUTIR, OUTDR, INI, IND, INIR, INDR must affect the carry flag.

**Comment by maziac** [comment]
Why do you think so?
E.g. this is from the Zilog specification for OUTD:
![Bildschirmfoto 2023-04-14 um 17 45 11](https://user-images.githubusercontent.com/3081973/232091691-5a162ec0-2c1e-4594-a7fe-381363af70ef.jpg)

**Comment by maziac** [comment]
Why do you think so?
This is from the zilog spec for outd:
![Bildschirmfoto 2023-04-14 um 17 47 52](https://user-images.githubusercontent.com/3081973/232092366-25c8c1ee-3131-4bdc-a63d-ba74dad15eb6.jpg)

**Comment by Tolik-Trek** [comment]
This is known information for a long time, and the documentation from zilog is not entirely accurate. You can test it on real hardware or in an emulator.
AND!
B <- B-1, (C) <- (HL), CF <- A-(HL), HL <- HL-1
)))

**Comment by maziac** [comment]
You have some reference.

**Comment by maziac** [comment]
Reference is [here](http://www.z80.info/zip/z80-documented.pdf)

**Comment by maziac** [comment]
Should be corrected now.
Please test this:
[z80-instruction-set-1.2.2-rc1.vsix.zip](https://github.com/maziac/z80-instruction-set/files/11239939/z80-instruction-set-1.2.2-rc1.vsix.zip)

**Comment by Tolik-Trek** [comment]
https://github.com/redcode/Z80/wiki/Technical-literature

https://zxe.io/depot/documents/technical/Undocumented%20Z80%20Flags%20rev1.0%20%282018-08-21%29%28Banks,%20David%29%28en%29%5B%21%5D.pdf

**Comment by Tolik-Trek** [comment]
> Should be corrected now. Please test this: [z80-instruction-set-1.2.2-rc1.vsix.zip](https://github.com/maziac/z80-instruction-set/files/11239939/z80-instruction-set-1.2.2-rc1.vsix.zip)

What about LD A,R or LD A,I ?

**Comment by maziac** [comment]
[z80-instruction-set-1.2.2-rc2.vsix.zip](https://github.com/maziac/z80-instruction-set/files/11241899/z80-instruction-set-1.2.2-rc2.vsix.zip)
Do you have more?

**Comment by Tolik-Trek** [comment]
https://github.com/redcode/Z80/wiki/Technical-literature

https://zxe.io/depot/documents/technical/Undocumented%20Z80%20Flags%20rev1.0%20%282018-08-21%29%28Banks,%20David%29%28en%29%5B%21%5D.pdf

I use these sources

**Comment by maziac** [comment]
Thanks for reporting.
