### ISSUE TITLE
Some inaccuracies

### ISSUE THREAD

**Issue by Tolik-Trek** [maziac/z80-instruction-set#17]
HI!
From Z80 Undocumented Features (in software behaviour) by Sean Young (sean@msxnet.org):
* The INI/INIR/IND/INDR/OUTI/OUTD/OTIR/OTDR instructions do affect the C
  flag (some official documentation says they leave it unaffected, 
  important!) and the N flag isn't always set but may also be reset (see 
  above for exact operation).
* IN x,(C) resets the H flag, it never sets it. Some documentation states
  it is set according to the result of the operation; bullocks, no
  arithmetic is done in this instruction.

[https://zxe.io/depot/documents/technical/Z80%20Undocumented%20Features%20%28In%20Software%20Behaviour%29%20v0.3%20%281998-10%29%28Young%2C%20Sean%29%28en%29%5B%21%5D.txt](url)

**Comment by maziac** [comment]
Could you please try this:
[z80-instruction-set-1.2.3-rc.vsix.zip](https://github.com/maziac/z80-instruction-set/files/14393170/z80-instruction-set-1.2.3-rc.vsix.zip)

**Comment by Tolik-Trek** [comment]
Perfect)))

**Comment by maziac** [comment]
Fixed in 1.2.3.
