### ISSUE TITLE
Not working when instruction followed by // style comment

### ISSUE THREAD

**Issue by oxidaan** [maziac/z80-instruction-set#9]
Does not work correctly when the instruction is followed by a // comment (like c++)
Some assemblers, like SjASMPlus, zeus do accept this form of comment notation.
I think following will fix it; at HoverUtils.ts line 22:
(checking two / after each other needed to avoid problems with eg: ld a, 4/16 )

    let len = 0;
    let prev = 0;
    for (const ch of rightString) {
        if (ch == ';' || ch == ':')
            break;
        if (ch == '/' && prev == '/')       // // is c++ style comment
        {
            len--;
            break;
        }
        prev = ch;            
        len++;
    }

**Comment by maziac** [comment]
Thanks for the fix. Will include it soon.

**Comment by oxidaan** [comment]
May just a simple single check for one slash will do, since it doesn't really matter if it takes just ld a,4 when the orginal code was ld a, 4/16.
Btw I did not test my code above, do not have the infrastructure yet to build vscode extensions...

**Comment by maziac** [comment]
Published it.
